<?php
$EM_CONF[$_EXTKEY] = [
    'title' => 'Cache Management Extension',
    'description' => 'Provides management of the page caching for high traffic websites.',
    'category' => 'module',
    'author' => 'AOE GmbH',
    'author_email' => 'dev@aoe.com',
    'shy' => '',
    'dependencies' => '',
    'conflicts' => '',
    'priority' => '',
    'module' => 'mod',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'author_company' => '',
    'version' => '4.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    '_md5_values_when_last_written' => '',
];
